language: android
android:
  components:
    - tools
    - platform-tools

    - build-tools-25.0.1

    - android-25

    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository

    - sys-img-armeabi-v7a-android-22

jdk: oraclejdk8
